apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: default
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-app
        image: 975050024946.dkr.ecr.ap-south-1.amazonaws.com/utkarsha-app-repo:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: ecr-secret   # Secret you created with kubectl create secret docker-registry
















# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: flask-deployment
#   namespace: default
#   labels:
#     app: flask
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: flask
#   template:
#     metadata:
#       labels:
#         app: flask
#     spec:
#       containers:
#       - name: flask-app
#         image: 975050024946.dkr.ecr.ap-south-1.amazonaws.com/utkarsha-app-repo:latest
#         ports:
#         - containerPort: 5000
#         resources:
#           requests:
#             memory: "128Mi"
#             cpu: "250m"
#           limits:
#             memory: "256Mi"
#             cpu: "500m"
#         livenessProbe:
#           httpGet:
#             path: /
#             port: 5000
#           initialDelaySeconds: 10
#           periodSeconds: 10
#         readinessProbe:
#           httpGet:
#             path: /
#             port: 5000
#           initialDelaySeconds: 5
#           periodSeconds: 5